### PR TITLE
Issue #33

### PR DESCRIPTION
**Pull request by daveeedu**
Adding responsiveness to voting page

### CODE REVIEW

**Comment by strakins** [comment]
Nice work

**Comment by strakins** [comment]
Your PR is to main, I guess u can check and review ur PR to dev 1st Sir

**Comment by daveeedu** [comment]
> Your PR is to main, I guess u can check and review ur PR to dev 1st Sir

I have rebased the PR to dev.

**Review by strakins — APPROVED** [review]
Nice work David

**Review by mehmetalicakir — APPROVED** [review]

**Pull request merged**
